name: Pylint, Black and Pytest pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest black

      - name: Format with black.
      - run: black backend/

      - name: Lint with Pylint
        run: pylint --output-format=json . > pylint.json
             pylint --fail-under=7 --recursive true .

      - name: Upload Pylint results
        uses: actions/upload-artifact@v3
        with:
          name: pylint-results
          path: pylint.json

  #test:
  #  runs-on: ubuntu-latest

  #  needs: lint

  # Z steps:
  #    - uses: actions/checkout@v3

  #    - name: Install dependencies
  #      run: |
  #        python -m pip install --upgrade pip
  #        pip install pytest

  #    - name: Run tests
  #      run: pytest
